# Generated by Django 5.2.8 on 2025-11-22 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('budget_alert', 'Budget Alert'), ('expense_alert', 'Expense Alert'), ('advisor_tip', 'Advisor Tip'), ('goal_milestone', 'Goal Milestone'), ('system', 'System Notification')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_budget_id', models.IntegerField(blank=True, help_text='ID of related budget', null=True)),
                ('related_expense_id', models.IntegerField(blank=True, help_text='ID of related expense', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to on click', max_length=255, null=True)),
                ('action_data', models.JSONField(blank=True, help_text='Additional data for frontend actions', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notify_noti_user_id_bc94cb_idx'), models.Index(fields=['user', '-created_at'], name='notify_noti_user_id_8a646a_idx')],
            },
        ),
    ]
